### ISSUE TITLE
Bimsurfer2 with Explode & Cross-section View

### ISSUE THREAD

**Issue by sagar-samanta-dignizant** [AECgeeks/BIMsurfer2#10]
Is there any API provided to implement explode and cross-section

**Comment by aothms** [comment]
Bimsurfer3 https://github.com/AECgeeks/BIMsurfer3 has a cross section functionality. Bimsurfer2 is based on ThreeJS, surely other people have worked on this, but there is nothing implemented directly in Bimsurfer2 at the moment. An exploded view is not implemented in either. Contributions are very welcome. Neither of these viewers are very actively developed at the moment, but are somewhat stable and in use in various applications.
