### ISSUE TITLE
BimSurfer2 + ifcOpenshell in React Application

### ISSUE THREAD

**Issue by akhil-dignizant** [AECgeeks/BIMsurfer2#9]
I need to create an IFC viewer app using ifcOpenShell and BimSurfer2. How can I integrate BimSurfer2 into a React app?

**Comment by aothms** [comment]
Maybe this helps https://www.reddit.com/r/reactjs/comments/15gsi91/comment/jukmpsv/

**Comment by akhil-dignizant** [comment]
Thanks for the response.

I can view my 3D file from my static folder in my React application. It's only for viewing the file, and I can also interact with the nodes while selecting. However, I also need to display the tree and data container when a node is selected. How can I achieve this?

**Comment by aothms** [comment]
This is out of scope of what we can support for as an open source community. I hope you're successful in your endeavours. If you have more specific questions at a later time about the code base as is we're happy to help.

**Comment by akhil-dignizant** [comment]
Thanks for the response.
